import Head from 'next/head'
import { useState, useEffect } from 'react';

export default function Home() {

  const [drinkFormState, setDrinkFormState] = useState({})
  const rootURL = process.env.NEXT_PUBLIC_API_URL

  const handleSubmit =async (e) => {
    e.preventDefault();
    try {
      const response = await fetch(`${rootURL}/api/drinks/`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(drinkFormState),
      });
      if (response.ok) {
        // Handle success, e.g., clear form or show a success message
      } else {
        // Handle errors, e.g., display an error message
      }
    } catch (error) {
      console.error('Error:', error);
    }
  }

  const handleChange = (e) => {
    const { name, value } = e.target;
    setDrinkFormState({
      ...drinkFormState,
      [name]: value,
    });
  };

  useEffect(() => {
    console.log(drinkFormState)
  }, [drinkFormState])
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-gray-200'>
        <h1 className='text-red-500'>Create a drink</h1>
        <form >
        <div>
          <label>Name</label>
          <input
            type="text"
            name="name"
            onChange={handleChange}
          />
        </div>
        <div>
          <label>Description</label>
          <input
            name="description"
            onChange={handleChange}
          />
        </div>
        <button type="submit" onClick={handleSubmit}>Submit</button>
      </form>

      </main>
    </>
  )
}
